spring:
    profiles: 
        active: 
        - dev
---
spring:
    profiles: dev 
    application:
        name: huadiaocloud-config-huadiao-dev
---        
spring:
    profiles: test
    application:
        name: huadiaocloud-config-huadiao-test